"""surface input

Revision ID: 34873a55d6c8
Revises: 879b93e9124b
Create Date: 2026-09-04 13:22:03.178376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34873a55d6c8'
down_revision: Union[str, Sequence[str], None] = '879b93e9124b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drawing_surfaces',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('drawing_case_id', sa.String(), nullable=False),
    sa.Column('treatment_option', sa.Enum('plating_only', 'plating_painting', name='surfacetreatmentoption'), nullable=True),
    sa.Column('plating_type', sa.Enum('standard', 'non_standard', name='platingtype'), nullable=True),
    sa.Column('plating_spec', sa.String(), nullable=True),
    sa.Column('painting_type', sa.Enum('acrylic_silicone', 'stain_coating', 'ceramic_coating', 'specified_color_paint', name='paintingtype'), nullable=True),
    sa.Column('color_name', sa.String(), nullable=True),
    sa.Column('munsell_value', sa.String(), nullable=True),
    sa.Column('color_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drawing_case_id'], ['drawing_cases.id'], name=op.f('fk_drawing_surfaces_drawing_case_id_drawing_cases'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drawing_surfaces')),
    sa.UniqueConstraint('drawing_case_id', name='uq_drawing_surface_case')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drawing_surfaces')
    # Drop enum types secara eksplisit (autogenerate tidak menuliskannya) —
    # tanpa ini, upgrade berikutnya gagal "type ... already exists".
    sa.Enum(name='surfacetreatmentoption').drop(op.get_bind())
    sa.Enum(name='platingtype').drop(op.get_bind())
    sa.Enum(name='paintingtype').drop(op.get_bind())
    # ### end Alembic commands ###
