"""init staging schema

Revision ID: 78d96043663e
Revises: 
Create Date: 2026-08-07 13:13:36.698921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78d96043663e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('superadmin', 'admin', 'drafter', name='role'), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.String(), nullable=False),
    sa.Column('is_verfied', sa.String(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('responsible_department_id', sa.String(), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.Column('reqeust_no', sa.String(), nullable=False),
    sa.Column('reciept_no', sa.String(), nullable=False),
    sa.Column('pj_no', sa.String(), nullable=False),
    sa.Column('request_type', sa.Enum('generally', 'special', name='requesttype'), nullable=False),
    sa.Column('design_type', sa.Enum('drawing', 'calculation', 'drawing_calculation', name='designtype'), nullable=False),
    sa.Column('request_category', sa.Enum('new', 'revision', name='requestcategory'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsible_department_id'], ['departments.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_id'), 'requests', ['id'], unique=False)
    op.create_table('calculation_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('supersedes_case_id', sa.String(), nullable=True),
    sa.Column('stauts', sa.Enum('draft', 'submitted', 'superseded', name='statuscase'), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_case_id'], ['calculation_cases.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculation_cases_id'), 'calculation_cases', ['id'], unique=False)
    op.create_table('drawing_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('supersedes_case_id', sa.String(), nullable=True),
    sa.Column('stauts', sa.Enum('draft', 'submitted', 'superseded', name='statuscase'), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_case_id'], ['drawing_cases.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drawing_cases_id'), 'drawing_cases', ['id'], unique=False)
    op.create_table('calculation_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('calculation_case_id', sa.String(), nullable=True),
    sa.Column('Status', sa.Enum('ok', 'ng', name='statuscalculationrun'), nullable=False),
    sa.Column('input_snapshot', sa.String(), nullable=True),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['calculation_case_id'], ['calculation_cases.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculation_runs_id'), 'calculation_runs', ['id'], unique=False)
    op.create_table('conditions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('calculation_case_id', sa.String(), nullable=True),
    sa.Column('design_standard', sa.Enum('jil', 'haiden', 'v60', name='designstandard'), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.Column('air_density', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['calculation_case_id'], ['calculation_cases.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conditions_id'), 'conditions', ['id'], unique=False)
    op.create_table('direct_objects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('calculation_case_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('front_area', sa.Float(), nullable=False),
    sa.Column('side_area', sa.Float(), nullable=False),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['calculation_case_id'], ['calculation_cases.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direct_objects_id'), 'direct_objects', ['id'], unique=False)
    op.create_table('high_evals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('calculation_case_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('point_evaluate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['calculation_case_id'], ['calculation_cases.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_high_evals_id'), 'high_evals', ['id'], unique=False)
    op.create_table('poles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('calculation_case_id', sa.String(), nullable=True),
    sa.Column('pole_type', sa.Enum('lighting', 'acemast', name='poletype'), nullable=True),
    sa.Column('standard', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['calculation_case_id'], ['calculation_cases.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poles_id'), 'poles', ['id'], unique=False)
    op.create_table('calculation_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('calculation_run_id', sa.String(), nullable=True),
    sa.Column('high_eval_id', sa.String(), nullable=True),
    sa.Column('total_moment', sa.Float(), nullable=False),
    sa.Column('total_windload', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ok', 'ng', name='statuscalculationrun'), nullable=False),
    sa.ForeignKeyConstraint(['calculation_run_id'], ['calculation_runs.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['high_eval_id'], ['high_evals.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculation_results_id'), 'calculation_results', ['id'], unique=False)
    op.create_table('step_poles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pole_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('diameter', sa.Float(), nullable=False),
    sa.Column('thickness', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('material', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pole_id'], ['poles.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_poles_id'), 'step_poles', ['id'], unique=False)
    op.create_table('direct_object_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('direct_object_id', sa.String(), nullable=True),
    sa.Column('calculation_result_id', sa.String(), nullable=True),
    sa.Column('windload', sa.Float(), nullable=False),
    sa.Column('moment', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['calculation_result_id'], ['calculation_results.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['direct_object_id'], ['direct_objects.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direct_object_results_id'), 'direct_object_results', ['id'], unique=False)
    op.create_table('pole_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('step_pole_id', sa.String(), nullable=True),
    sa.Column('calculation_result_id', sa.String(), nullable=True),
    sa.Column('windload', sa.Float(), nullable=False),
    sa.Column('moment', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['calculation_result_id'], ['calculation_results.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_pole_id'], ['step_poles.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pole_results_id'), 'pole_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pole_results_id'), table_name='pole_results')
    op.drop_table('pole_results')
    op.drop_index(op.f('ix_direct_object_results_id'), table_name='direct_object_results')
    op.drop_table('direct_object_results')
    op.drop_index(op.f('ix_step_poles_id'), table_name='step_poles')
    op.drop_table('step_poles')
    op.drop_index(op.f('ix_calculation_results_id'), table_name='calculation_results')
    op.drop_table('calculation_results')
    op.drop_index(op.f('ix_poles_id'), table_name='poles')
    op.drop_table('poles')
    op.drop_index(op.f('ix_high_evals_id'), table_name='high_evals')
    op.drop_table('high_evals')
    op.drop_index(op.f('ix_direct_objects_id'), table_name='direct_objects')
    op.drop_table('direct_objects')
    op.drop_index(op.f('ix_conditions_id'), table_name='conditions')
    op.drop_table('conditions')
    op.drop_index(op.f('ix_calculation_runs_id'), table_name='calculation_runs')
    op.drop_table('calculation_runs')
    op.drop_index(op.f('ix_drawing_cases_id'), table_name='drawing_cases')
    op.drop_table('drawing_cases')
    op.drop_index(op.f('ix_calculation_cases_id'), table_name='calculation_cases')
    op.drop_table('calculation_cases')
    op.drop_index(op.f('ix_requests_id'), table_name='requests')
    op.drop_table('requests')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
