"""init staging schema

Revision ID: b917cdf4c8bd
Revises: 
Create Date: 2026-08-20 16:21:15.562483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b917cdf4c8bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author_codes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department_codes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lighting_company_codes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('object_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pole_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region_codes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('design_standards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pole_category_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('default_wind_speed', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('default_air_density', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pole_category_id'], ['pole_categories.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pole_standards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pole_category_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('taper', 'straight', name='polestandardtype'), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pole_category_id'], ['pole_categories.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('superadmin', 'admin', 'drafter', name='role'), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pole_diameters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pole_standard_id', sa.String(), nullable=False),
    sa.Column('diameter', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pole_standard_id'], ['pole_standards.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pole_standard_heights',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pole_standard_id', sa.String(), nullable=False),
    sa.Column('ground_position', sa.Enum('on_GL', 'under_GL', name='poleheightgroundposition'), nullable=False),
    sa.Column('height', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pole_standard_id'], ['pole_standards.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('responsible_department_id', sa.String(), nullable=False),
    sa.Column('created_by_user_id', sa.String(), nullable=False),
    sa.Column('pole_category_id', sa.String(), nullable=False),
    sa.Column('request_no', sa.String(), nullable=False),
    sa.Column('receipt_no', sa.String(), nullable=False),
    sa.Column('pj_no', sa.String(), nullable=False),
    sa.Column('request_type', sa.Enum('generally', 'special', name='requesttype'), nullable=False),
    sa.Column('design_type', sa.Enum('drawing', 'calculation', 'drawing_calculation', name='designtype'), nullable=False),
    sa.Column('request_category', sa.Enum('new', 'revision', 'modification', 'replacement', name='requestcategory'), nullable=False),
    sa.Column('pole_kind', sa.Enum('standard', 'custom', name='polekind'), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pole_category_id'], ['pole_categories.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responsible_department_id'], ['departments.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drawing_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('supersedes_case_id', sa.String(), nullable=True),
    sa.Column('lighting_company_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'superseded', name='statusdrawingcase'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('drawing_type', sa.String(), nullable=False),
    sa.Column('drawing_number', sa.String(), nullable=False),
    sa.Column('part_number', sa.String(), nullable=False),
    sa.Column('designer_name', sa.String(), nullable=False),
    sa.Column('checked_by_name', sa.String(), nullable=False),
    sa.Column('approved_by_name', sa.String(), nullable=False),
    sa.Column('coupling', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lighting_company_id'], ['lighting_company_codes.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_case_id'], ['drawing_cases.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pole_combinations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pole_diameter_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pole_diameter_id'], ['pole_diameters.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calculation_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('supersedes_case_id', sa.String(), nullable=True),
    sa.Column('pole_standard_id', sa.String(), nullable=True),
    sa.Column('pole_standard_height_id', sa.String(), nullable=True),
    sa.Column('pole_combination_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'superseded', name='statuscalculationcase'), nullable=False),
    sa.Column('pole_family', sa.Enum('taper', 'straight', name='polefamily'), nullable=True),
    sa.Column('ground_position', sa.Enum('embedment', 'on_GL', 'upper_GL', 'under_GL', name='groundposition'), nullable=True),
    sa.Column('lowest_height', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('embedment_length', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('overdesign_factor', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pole_combination_id'], ['pole_combinations.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pole_standard_height_id'], ['pole_standard_heights.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pole_standard_id'], ['pole_standards.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_case_id'], ['calculation_cases.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pole_thicknesses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pole_combination_id', sa.String(), nullable=False),
    sa.Column('position', sa.Enum('upper', 'lower', name='polethicknessposition'), nullable=False),
    sa.Column('thickness', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pole_combination_id'], ['pole_combinations.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('calculation_case_id', sa.String(), nullable=False),
    sa.Column('material_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('diameter', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('thickness', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('length', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('exp_length', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('height', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('distance', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('nnc', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('fix_angle', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['calculation_case_id'], ['calculation_cases.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_plates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('calculation_case_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('four_rib', 'eight_rib', name='baseplatetype'), nullable=False),
    sa.Column('base_plate_width', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('anchor_pitch', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('achor_bolt_diameter', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('base_plate_thickness', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('rib_plate_height', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('rib_plate_length', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('rib_plate_thickness', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('rib_plate_scallop', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('rib_plate_angle', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('weld_leg_length', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.ForeignKeyConstraint(['calculation_case_id'], ['calculation_cases.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calculation_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('calculation_case_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ok', 'ng', name='statuscalculationrun'), nullable=False),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['calculation_case_id'], ['calculation_cases.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conditions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('calculation_case_id', sa.String(), nullable=False),
    sa.Column('design_standard_id', sa.String(), nullable=False),
    sa.Column('wind_speed', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('air_density', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.ForeignKeyConstraint(['calculation_case_id'], ['calculation_cases.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['design_standard_id'], ['design_standards.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('direct_objects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('calculation_case_id', sa.String(), nullable=False),
    sa.Column('object_type_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('front_area', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('height', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('nnc', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['calculation_case_id'], ['calculation_cases.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_type_id'], ['object_types.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foundations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('calculation_case_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('square', 'circle', name='foundationtype'), nullable=False),
    sa.Column('embedment_depth', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('n_value', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('gamma_c', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('gamma', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('alpha', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('foundation_width_x', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('foundation_width_y', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('foundation_width', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.ForeignKeyConstraint(['calculation_case_id'], ['calculation_cases.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opening_parts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('calculation_case_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('box', 'r', name='openingtype'), nullable=False),
    sa.Column('opening_width', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('box_width', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('opening_suerface_height', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('box_thickness', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('opening_length', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.ForeignKeyConstraint(['calculation_case_id'], ['calculation_cases.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('overhead_wires',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('calculation_case_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('diameter', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('fix_height', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('span', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('sagging_ration', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('nnc', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('fix_angle', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('vertical_angle', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.ForeignKeyConstraint(['calculation_case_id'], ['calculation_cases.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('calculation_case_id', sa.String(), nullable=False),
    sa.Column('region_code_id', sa.String(), nullable=False),
    sa.Column('department_code_id', sa.String(), nullable=True),
    sa.Column('author_code_id', sa.String(), nullable=True),
    sa.Column('report_number', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('design_request_management_no', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('report_title_1', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('report_title_2', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('report_title_3', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_code_id'], ['author_codes.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['calculation_case_id'], ['calculation_cases.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_code_id'], ['department_codes.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_code_id'], ['region_codes.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('step_poles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('calculation_case_id', sa.String(), nullable=False),
    sa.Column('material_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('diameter', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('thickness', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('height', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['calculation_case_id'], ['calculation_cases.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arm_objects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('arm_id', sa.String(), nullable=False),
    sa.Column('object_type_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('front_area', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('distance', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('nnc', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arm_id'], ['arms.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_type_id'], ['object_types.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calculation_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('calculation_run_id', sa.String(), nullable=False),
    sa.Column('total_moment', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('total_windload', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('status', sa.Enum('ok', 'ng', name='statuscalculationrun'), nullable=False),
    sa.ForeignKeyConstraint(['calculation_run_id'], ['calculation_runs.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('direct_object_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('direct_object_id', sa.String(), nullable=False),
    sa.Column('calculation_result_id', sa.String(), nullable=False),
    sa.Column('windload', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('moment', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.ForeignKeyConstraint(['calculation_result_id'], ['calculation_results.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['direct_object_id'], ['direct_objects.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pole_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('step_pole_id', sa.String(), nullable=False),
    sa.Column('calculation_result_id', sa.String(), nullable=False),
    sa.Column('windload', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('moment', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.ForeignKeyConstraint(['calculation_result_id'], ['calculation_results.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_pole_id'], ['step_poles.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pole_results')
    op.drop_table('direct_object_results')
    op.drop_table('calculation_results')
    op.drop_table('arm_objects')
    op.drop_table('step_poles')
    op.drop_table('reports')
    op.drop_table('overhead_wires')
    op.drop_table('opening_parts')
    op.drop_table('foundations')
    op.drop_table('direct_objects')
    op.drop_table('conditions')
    op.drop_table('calculation_runs')
    op.drop_table('base_plates')
    op.drop_table('arms')
    op.drop_table('pole_thicknesses')
    op.drop_table('calculation_cases')
    op.drop_table('pole_combinations')
    op.drop_table('drawing_cases')
    op.drop_table('requests')
    op.drop_table('pole_standard_heights')
    op.drop_table('pole_diameters')
    op.drop_table('users')
    op.drop_table('pole_standards')
    op.drop_table('design_standards')
    op.drop_table('region_codes')
    op.drop_table('pole_categories')
    op.drop_table('object_types')
    op.drop_table('materials')
    op.drop_table('lighting_company_codes')
    op.drop_table('departments')
    op.drop_table('department_codes')
    op.drop_table('author_codes')
    # ### end Alembic commands ###
