"""department code and uniques

Revision ID: f57b3420d97e
Revises: 37dbea1cea8a
Create Date: 2026-08-27 10:12:45.697669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f57b3420d97e'
down_revision: Union[str, Sequence[str], None] = '37dbea1cea8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('code', sa.String(), nullable=False))
    op.create_unique_constraint(op.f('uq_departments_code'), 'departments', ['code'])
    op.create_unique_constraint(op.f('uq_departments_name'), 'departments', ['name'])
    op.drop_constraint(op.f('refresh_tokens_token_hash_key'), 'refresh_tokens', type_='unique')
    op.create_unique_constraint(op.f('uq_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'])
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_refresh_tokens_token_hash'), 'refresh_tokens', type_='unique')
    op.create_unique_constraint(op.f('refresh_tokens_token_hash_key'), 'refresh_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_departments_name'), 'departments', type_='unique')
    op.drop_constraint(op.f('uq_departments_code'), 'departments', type_='unique')
    op.drop_column('departments', 'code')
    # ### end Alembic commands ###
